ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;
CREATE USER your_db_name IDENTIFIED BY "your db password"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT DBA TO dbfinal;
  ALTER USER dbfinal DEFAULT ROLE ALL;
  ALTER USER dbfinal QUOTA UNLIMITED ON USERS;
  GRANT CREATE ROLE TO dbfinal;
  GRANT CREATE USER TO dbfinal;
  GRANT CREATE SESSION TO dbfinal;
  



